//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osma.Mobile.App {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osma.Mobile.App.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account.
        /// </summary>
        public static string AccountTabTitle {
            get {
                return ResourceManager.GetString("AccountTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connections.
        /// </summary>
        public static string ConnectionsPageTitle {
            get {
                return ResourceManager.GetString("ConnectionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connections.
        /// </summary>
        public static string ConnectionsTabTitle {
            get {
                return ResourceManager.GetString("ConnectionsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        public static string ConnectionStateConnected {
            get {
                return ResourceManager.GetString("ConnectionStateConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invited.
        /// </summary>
        public static string ConnectionStateInvited {
            get {
                return ResourceManager.GetString("ConnectionStateInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Negotiating.
        /// </summary>
        public static string ConnectionStateNegotiating {
            get {
                return ResourceManager.GetString("ConnectionStateNegotiating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create invitation.
        /// </summary>
        public static string CreateInvitationToolbarItemLabel {
            get {
                return ResourceManager.GetString("CreateInvitationToolbarItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credentials.
        /// </summary>
        public static string CredentialsPageTitle {
            get {
                return ResourceManager.GetString("CredentialsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credentials.
        /// </summary>
        public static string CredentialsTabTitle {
            get {
                return ResourceManager.GetString("CredentialsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Issued.
        /// </summary>
        public static string CrendentialIssuedLabel {
            get {
                return ResourceManager.GetString("CrendentialIssuedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string DeleteConnectionButton {
            get {
                return ResourceManager.GetString("DeleteConnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        public static string ProofRequestTitle {
            get {
                return ResourceManager.GetString("ProofRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proofs.
        /// </summary>
        public static string ProofsPageTitle {
            get {
                return ResourceManager.GetString("ProofsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proofs.
        /// </summary>
        public static string ProofsTabTitle {
            get {
                return ResourceManager.GetString("ProofsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accepted.
        /// </summary>
        public static string ProofStateAccepted {
            get {
                return ResourceManager.GetString("ProofStateAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proposed.
        /// </summary>
        public static string ProofStateProposed {
            get {
                return ResourceManager.GetString("ProofStateProposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejected.
        /// </summary>
        public static string ProofStateRejected {
            get {
                return ResourceManager.GetString("ProofStateRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requested.
        /// </summary>
        public static string ProofStateRequested {
            get {
                return ResourceManager.GetString("ProofStateRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan.
        /// </summary>
        public static string ScanToolbarItemLabel {
            get {
                return ResourceManager.GetString("ScanToolbarItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search credentials.
        /// </summary>
        public static string SearchCredentialsPlaceholder {
            get {
                return ResourceManager.GetString("SearchCredentialsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search proof requests.
        /// </summary>
        public static string SearchProofRequestsPlaceholder {
            get {
                return ResourceManager.GetString("SearchProofRequestsPlaceholder", resourceCulture);
            }
        }
    }
}
